importtoexportdjango/urls.py
from django.conf.urls import *
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from main.views import HomeView, CategoryView, NewsDetailView, VideosView
from django.conf.urls import *
from django.http import HttpResponse
from main import views
from django.contrib.sitemaps.views import sitemap
from main.sitemaps import StaticViewSitemap, CategoryViewSiteMap, NewViewSiteMap

sitemaps = {
    'static': StaticViewSitemap,
    'categories': CategoryViewSiteMap,
    'single_new': NewViewSiteMap,
}


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^$', views.landing, name="landing"),
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^videos', VideosView.as_view(), name="videos_view"),
    url(r'^(?P<slug>[\w\-]+)/$', CategoryView.as_view(), name="category_view"),
    #url(r'^noticia/(?P<slug>[\w\-]+)/$', NewsDetailView.as_view(), name="news_detail"),
    #url(r'^(?P<catslug>[\w\-]+)/(?P<slug>[\w\-]+)/$', NewsDetailView.as_view(), name="news_detail"),
    url(r'^(?P<category>[\w\-]+)/(?P<slug>[\w\-]+)/$', NewsDetailView.as_view(), name="news_detail"),
    url(r'^suscripcion', views.contactUs, name="suscripcion"),
    url(r'^franquiciatario', views.franquiciatario, name="franquiciatario"),
    url(r'^search_news', views.search_news, name='search_news'),
    url(r'^tag/(?P<tag_name>[-\w]+)', views.tagged_posts, name='tag'),
    url(r'^aviso-de-privacidad', views.terms_and_conditions, name='terms_and_conditions'),
    url(r'^registro-exitoso', views.registrok, name="registrok"),
    url(r'^datos-enviados', views.datos_enviados, name="datos_enviados"),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns.append(url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

main/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.template.defaultfilters import slugify
from autoslug import AutoSlugField
from functools import reduce
from tagging.fields import TagField
from tagging.models import Tag


# Create your models here.
def get_model_attr(instance, attr):
    """Example usage: get_model_attr(instance, 'category__slug')"""
    for field in attr.split('__'):
        instance = getattr(instance, field)
    return instance

class Test(models.Model):
    date = models.DateField()
    title = models.TextField()

class Author(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)

    def __unicode__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)

    def __unicode__(self):
        return self.name

class Book(models.Model):
    name = models.CharField('Book name', max_length=100)
    author = models.ForeignKey(Author, blank=True, null=True)
    author_email = models.EmailField('Author email', max_length=75, blank=True)
    imported = models.BooleanField(default=False)
    published = models.DateField('Published', blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    categories = models.ManyToManyField(Category, blank=True)

    def __unicode__(self):
        return self.name

class PromotionBanner(models.Model):
    titulo = models.CharField(max_length=100, blank=True, null=True)
    banner_url = models.CharField(max_length=1000, blank=True)
    banner_image = models.ImageField(upload_to='Images/PromotionBanners/')
    def __unicode__(self):
        return self.titulo

class BannerInSection(models.Model):
    titulo = models.CharField(max_length=100, blank=True, null=True)
    def __unicode__(self):
        return self.titulo

class BannerItem(models.Model):
    titulo = models.CharField(max_length=50,blank=True,null=True)
    descripcion = models.CharField(max_length=250, blank=True)
    slide_url = models.CharField(max_length=500, blank=True)
    image = models.ImageField(upload_to='Images/Benner/Items/')
    banner_in_section = models.ForeignKey(BannerInSection, blank=True, null=True)
    def __unicode__(self):
        return self.titulo

class SectionSlide(models.Model):
    nombre = models.CharField(max_length=100, blank=True, null=True)
    def __unicode__(self):
        return self.nombre

class SectionSlideItem(models.Model):
    titulo = models.CharField(max_length=50,blank=True,null=True)
    descripcion = models.CharField(max_length=250, blank=True)
    slide_url = models.CharField(max_length=500, blank=True)
    image = models.ImageField(upload_to='Images/Section/Slide/')
    section_slide = models.ForeignKey(SectionSlide, blank=True, null=True)
    def __unicode__(self):
        return self.titulo

class SectionFetiche(models.Model):
    titulo = models.CharField(max_length=50,blank=True, null=True)
    def __unicode__(self):
        return self.titulo

class FeticheItem(models.Model):
    titulo = models.CharField(max_length=50,blank=True,null=True)
    image = models.ImageField(upload_to='Images/Section/Fetiche/')
    section_fetiche = models.ForeignKey(SectionFetiche, blank=True, null=True)
    def __unicode__(self):
        return self.titulo

# class Tag(models.Model):
#     name = models.CharField('Tags name', max_length=100,blank=True, null=True)

#     def __unicode__(self):
#         return self.name

# class TagItem(models.Model):
#     tag_texto = models.CharField('Tag', max_length=30, blank=True, null=True)
#     tag = models.ForeignKey(Tag, blank=True, null=True)
#     def __unicode__(self):
#         return self.tag_texto

class Metatag(models.Model):
    titulo = models.CharField(max_length=100,blank=True, null=True)
    descripcion = models.CharField(max_length=1000,blank=True)
    keywords = models.CharField(max_length=1000,blank=True)
    def __unicode__(self):
        return self.titulo

class Video(models.Model):
    titulo = models.CharField(max_length=200, blank=True, null=True)
    descripcion = RichTextField(max_length=10000, blank=True, null=True)
    id_video = models.CharField(max_length=20, blank=True)

class Section(models.Model):
    titulo = models.CharField('Nombre de Seccion', max_length=100, null=True)
    descripcion = RichTextField(max_length=10000, blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    section_slide = models.ForeignKey(SectionSlide, blank=True, null=True)
    banner = models.ForeignKey(BannerInSection, blank=True, null=True)
    promotion_banner = models.ForeignKey(PromotionBanner, blank=True, null=True)
    metatag = models.ForeignKey(Metatag, blank=True, null=True)
    section_fetiche = models.ForeignKey(SectionFetiche, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.titulo)
        super(Section, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.titulo

class CategoryNew(models.Model):
    name = models.CharField('Nombre de Categoria', max_length=100, blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    category_slide = models.ForeignKey(SectionSlide, blank=True, null=True)
    banner = models.ForeignKey(BannerInSection, blank=True, null=True)
    promotion_banner = models.ForeignKey(PromotionBanner, blank=True, null=True)
    metatag = models.ForeignKey(Metatag, blank=True, null=True)
    section_fetiche = models.ForeignKey(SectionFetiche, blank=True, null=True)
    promotion_banner = models.ForeignKey(PromotionBanner, blank=True, null=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(CategoryNew, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('category_view', kwargs={'slug': self.slug})

    def __unicode__(self):
        return self.name


def next_or_prev_in_order(instance, prev=False, qs=None, loop=False):
    """Get the next (or previous with prev=True) item for instance, from the
       given queryset (which is assumed to contain instance) respecting
       queryset ordering. If loop is True, return the first/last item when the
       end/start is reached. """

    if not qs:
        qs = instance.__class__.objects
    if prev:
        qs = qs.reverse()
        lookup = 'lt'
    else:
        lookup = 'gt'

    q_list = []
    prev_fields = []
    if qs.model._meta.ordering:
        ordering = list(qs.model._meta.ordering)
    else:
        ordering = []

    for field in (ordering + ['pk']):
        if field[0] == '-':
            this_lookup = (lookup == 'gt' and 'lt' or 'gt')
            field = field[1:]
        else:
            this_lookup = lookup
        q_kwargs = dict([(f, get_model_attr(instance, f))
                         for f in prev_fields])
        key = "%s__%s" % (field, this_lookup)
        q_kwargs[key] = get_model_attr(instance, field)
        q_list.append(models.Q(**q_kwargs))
        prev_fields.append(field)
    try:
        return qs.filter(reduce(models.Q.__or__, q_list))[0]
    except IndexError:
        length = qs.count()
        if loop and length > 1:
            # queryset is reversed above if prev
            return qs[0]
    return None


class New(models.Model):
    titulo = models.CharField('News name', max_length=10000)
    categoria = models.ForeignKey(CategoryNew, related_name='children')
    imagen_thumbnail = models.ImageField(upload_to="images", blank=True, null=True)
    #imagen_slide = models.ImageField(upload_to="images", blank=True, null=True)
    imagen1 = models.ImageField(upload_to="images", blank=True, null=True)
    sumario = models.TextField(max_length=10000, blank=True, null=True)
    texto1 = RichTextField(max_length=10000, blank=True, null=True)
    imagen2 = models.ImageField(upload_to="images", blank=True, null=True)
    texto2 = RichTextField(max_length=10000, blank=True, null=True)
    destacado1 = models.TextField(max_length=10000, blank=True, null=True)
    texto3 = RichTextField(max_length=10000, blank=True, null=True)
    imagen3 = models.ImageField(upload_to="images", blank=True, null=True)
    texto4 = RichTextField(max_length=10000, blank=True, null=True)
    destacado2 = models.TextField(max_length=10000, blank=True, null=True)
    texto5 = RichTextField(max_length=10000, blank=True, null=True)
    imagen4 = models.ImageField(upload_to="images", blank=True, null=True)
    texto6 = RichTextField(max_length=10000, blank=True, null=True)
    texto7 = RichTextField(max_length=10000, blank=True, null=True)
    imagen5 = models.ImageField(upload_to="images", blank=True, null=True)
    #etiquetas = models.ForeignKey(Tag, blank=True, null=True)
    tags = TagField()
    date = models.DateField('Published', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    #slug = AutoSlugField(populate_from=titulo, unique_with='categoria_slug',blank=True, null=True, editable=True)
    metatag = models.ForeignKey(Metatag, blank=True, null=True)
    
    
    def get_tags(self):
        return Tag.objects.get_for_object(self)

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.titulo)
    #     super(New, self).save(*args, **kwargs)

    def get_previous(self):
        """
        Returns the previous element of the list using the current index if it exists.
        Otherwise returns an empty string.
        """
        qs = self.__class__.objects.filter(categoria=self.categoria).order_by('pk')
        return next_or_prev_in_order(self, True, qs)
        # previous = self.__class__.objects.filter(pk__lt=self.pk)
        # try:
        #     return previous[0]
        # except IndexError:
        #     return False

    def get_next(self):
        """

main/forms.py
from django import forms

class FormBuscarElementos(forms.Form):
	term = forms.CharField(max_length=100)

class FormContacto(forms.Form):
    user_name = forms.CharField(max_length=100, required=True)
    user_sex = forms.CharField(max_length=13, required=True)
    user_age = forms.CharField(max_length=80, required=False)
    user_city = forms.CharField(max_length=80, required=True)
    user_state = forms.CharField(max_length=80, required=False)
    user_email = forms.EmailField(required=True)

class FormFranquiciatario(forms.Form):
    user_name = forms.CharField(max_length=100, required=True)
    user_email = forms.EmailField(required=True)
    user_phone_number = forms.CharField(required=True, max_length=20)
    user_message = forms.CharField(widget=forms.Textarea, max_length=250,required=False)

main/templates/category.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block bodyclass %}qpsp-{{ section.slug }}{% endblock %}

{% block title %}{{ section.metatag.titulo }}{% endblock %}
{% block site_keywords %}{{section.metatag.keywords}}{% endblock %}
{% block site_description %}{{section.metatag.descripcion|safe}}{% endblock %}

{% block metatags %}
<!--Facebook-->
<meta property="og:url"         content="http://quepadreserpadres.com" />
<meta property="og:type"        content="" />
<meta property="og:title"       content="{{section.metatag.titulo}}" />
<meta property="og:description" content="{{section.metatag.descripcion|striptags|safe}}" />
<meta property="og:image"       content="" />
<!--Twiter-->
<meta name="twitter:card"       value="">
<meta name="twitter:creator"    value="Punk e-Marketing & Consulting">
<meta name="twitter:url"        value="http://quepadreserpadres.com">
<meta name="twitter:title"       value="{{section.metatag.titulo}}">
<meta name="twitter:description" value="{{section.metatag.descripcion|striptags|safe}}" />
<meta name="twitter:image"       value="">
{% endblock %}

{% block content %}
	<section class="slider-content row">
		<div class="container-fluid withinpadding">
			<div class="carousel fade-carousel slide" data-ride="carousel" data-interval="8000" id="bs-carousel">
			  <!-- Overlay -->
			  <!--div class="overlay"></div-->
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
			  </ol>
			  <!-- Wrapper for slides -->
			  <div class="carousel-inner">
			  	{% for slide_item in section.category_slide.sectionslideitem_set.all %}
			  		<div class="item slides">
				      <div class="slide-1">
				      	<img src="/media/{{ slide_item.image }}" class="img-responsive" alt="{{ slide_item.titulo|safe }}" title="{{ slide_item.titulo|safe }}">
				      </div>
				      <div class="hero col-md-5 col-sm-5">
				        <hgroup>
				            <h2>{{ slide_item.titulo }}</h2>        
				            <p>{{ slide_item.descripcion|safe|truncatewords:12 }}...</p>
				        </hgroup>
				        <a href="/{{ slide_item.slide_url }}" style="color:white">
				        	<button class="btn btn-hero btn-lg" role="button">IR AL ARTÍCULO</button>
			        	</a>
				      </div>
				    </div>
			  	{% endfor %}
			  </div> 
			</div>
		</div>
	</section>
	<section class="articles-content row">
		<div class="container">
			<div class="col-md-9 col-sm-9 col-xs-12">
				<div class="row">
					<h1 class="text-center page-title">{{section.name}}</h1>
				</div>
				<!-- <h1>Choose your favorite module</h1> -->
				<div class="row">
					<div class="col-md-12 list_of_articles">
						<div class="masonry-grid">
							{% for new in noticias %}
							<div class="grid-item article-item col-md-6 col-sm-6 col-xs-12">
								<a href="{% url 'news_detail' new.categoria.slug new.slug %}">
									<img src="/media/{{ new.imagen_thumbnail }}" class="img-responsive">
									<div class="article-description">
										<h2 class="text-center news-title">{{ new.titulo|safe }}</h2>
										<p>{{ new.texto1|striptags|safe|truncatewords:20 }}</p>
										<p class="text-center"><a class="leermas" href="{% url 'news_detail' new.categoria.slug new.slug %}">LEER MÁS</a></p>
									</div>
								</a>
							</div>
								{% if forloop.counter|divisibleby:3 and forloop.counter < 4 %}
								<div class="grid-item article-item text-center col-md-6 col-sm-6 col-xs-12 imgthird">
											<img src="/media/{{ section_fetiche.0.image }}" class="img-cat" alt="{{ section_fetiche.0.titulo }}" title="{{ section_fetiche.0.titulo }}" style="margin:0 auto;">
										</div>
								{% endif %}
								{% if forloop.counter|divisibleby:6 and forloop.counter < 7 %}
								<div class="grid-item article-item text-center col-md-6 col-sm-6 col-xs-12">
											<img src="/media/{{ section_fetiche.1.image }}" class="img-cat" alt="{{ section_fetiche.1.titulo }}" title="{{ section_fetiche.1.titulo }}" style="margin:0 auto;">
										</div>
								{% endif %}
								{% if forloop.counter|divisibleby:9 and forloop.counter < 10 %}
								<div class="grid-item article-item text-center col-md-6 col-sm-6 col-xs-12">
											<img src="/media/{{ section_fetiche.2.image }}" class="img-cat" alt="{{ section_fetiche.2.titulo }}" title="{{ section_fetiche.2.titulo }}" style="margin:0 auto;">
										</div>
								{% endif %}	
							{% endfor %}
							<!--div class="grid-item">
								<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/orange-tree.jpg" />
							</div-->
						</div>
					</div>
				</div>
				{% if is_paginated %}
				<div class="row text-center">
				  <ul class="pagination">
				    {% if page_obj.has_previous %}
				      <li><a href="?page={{ page_obj.previous_page_number }}"><i class="icon-triangle-left"></i></a></li>
				    {% else %}
				      <li class="disabled"><a href="#"><i class="icon-triangle-left"></i></a></li>
				    {% endif %}

				    {% for num in page_obj.paginator.page_range %}
				      {% ifequal num page_obj.number %}
				        <li class="active"><a href="#">{{ num }}<span class="sr-only">(current)</span></a></li>
				      {% else %}
				        <li><a href="?page={{ num }}">{{ num }}</a></li>
				      {% endifequal %}
				    {% endfor %}

				    {% if page_obj.has_next %}
				      <li><a href="?page={{ page_obj.next_page_number }}"><i class="icon-triangle-right"></i></a></li>
				    {% else %}
				      <li class="disabled"><a href="#"><i class="icon-triangle-right"></i></a></li>
				    {% endif %}
				  <ul>
				</div>
				{% endif %}
			</div>
			<div class="col-md-3 col-sm-3 col-xs-12">
				{% include "rightbar.html" %}  
			</div>
		</div>
	</section>	
{% endblock %}
{% block js %}
<script type="text/javascript">
$('.carousel .carousel-inner .item:eq(0)').addClass('active');
for (var i=1; i<=$("#fullpageservices").children().length;i++)
{
    var parimpar ="par";
    if(i%2){
        parimpar = "impar";
    }
    $('#fullpageservices .fp-tableCell .items:eq('+(i-1)+')').addClass('row-'+parimpar);
}
//alert('{{section.section_slide.sectionslideitem_set.all.count}}');
var slide_length = '{{section.category_slide.sectionslideitem_set.all.count}}';
for ( var i = 0; i < slide_length; i++ ){
	$('.carousel-indicators').append('<li data-target="#bs-carousel" data-slide-to="'+i+'" class=""></li>');
}
$('ol.carousel-indicators li:eq(0)').addClass('active');
$(function() {
	$('nav a[href^="/' + location.pathname.split("/")[1] + '"]').addClass('active');
});

$('.list_of_articles .article-item:last img.img-cat').css('display','none');
</script>
{% endblock %}

main/templates/datos-enviados.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block bodyclass %}qpsp-home{% endblock %}
{% block content %}
	<section class="single-page-article row">
		<div class="container">
			<div class="col-md-8 col-md-offset-2 col-sm-offset-2 col-sm-9  col-xs-12">
				<div class="row article-full-content terms-and-cond">
					<h1 class="text-center page-title">
						¡GRACIAS POR ENVIARNOS TUS DATOS! Pronto nos comunicaremos contigo.
					</h1>
				</div>		
			</div>
		</div>
	</section>
{% endblock %}

main/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{{ section.metatag.titulo }}{% endblock %}
{% block site_keywords %}{{section.metatag.keywords}}{% endblock %}
{% block site_description %}{{section.metatag.descripcion|safe}}{% endblock %}

{% block metatags %}
<!--Facebook-->
<meta property="og:url"         content="http://quepadreserpadres.com" />
<meta property="og:type"        content="" />
<meta property="og:title"       content="{{section.metatag.titulo}}" />
<meta property="og:description" content="{{section.metatag.descripcion|striptags|safe}}" />
<meta property="og:image"       content="" />
<!--Twiter-->
<meta name="twitter:card"       value="">
<meta name="twitter:creator"    value="Punk e-Marketing & Consulting">
<meta name="twitter:url"        value="http://quepadreserpadres.com">
<meta name="twitter:title"       value="{{section.metatag.titulo}}">
<meta name="twitter:description" value="{{section.metatag.descripcion|striptags|safe}}" />
<meta name="twitter:image"       value="">
{% endblock %}

{% block bodyclass %}qpsp-home{% endblock %}
{% block content %}
	<section class="slider-content row">
		<div class="container-fluid withinpadding">
			<div class="carousel fade-carousel slide" data-ride="carousel" data-interval="8000" id="bs-carousel">
			  <!-- Overlay -->
			  <!--div class="overlay"></div-->
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
			  </ol>
			  <!-- Wrapper for slides -->
			  <div class="carousel-inner">
			  	{% for slide_item in section.section_slide.sectionslideitem_set.all %}
			  		<div class="item slides">
				      <div class="slide-1">
				      	<img src="/media/{{ slide_item.image }}" class="img-responsive" alt="{{ slide_item.titulo|safe }}" title="{{ slide_item.titulo|safe }}">
				      </div>
				      <div class="hero col-md-5 col-sm-5">
				        <hgroup>
				            <h2>{{ slide_item.titulo }}</h2>        
				            <p>{{ slide_item.descripcion|safe|truncatewords:12 }}...</p>
				        </hgroup>
				        <a href="{{ slide_item.slide_url }}" style="color:white">
				        	<button class="btn btn-hero btn-lg" role="button">IR AL ARTÍCULO</button>
			        	</a>
				      </div>
				    </div>
			  	{% endfor %}
			  </div> 
			</div>
		</div>
	</section>
	<section class="articles-content row">
		<div class="container">
			<div class="col-md-9 col-sm-9 col-xs-12">
				<div class="row">
					<h1 class="text-center page-title">ÚLTIMOS ARTÍCULOS</h1>
					
				</div>
				<!-- <h1>Choose your favorite module</h1> -->
				<div class="row">
					<div class="col-md-12 list_of_articles">
						<div class="masonry-grid">
							{% for new in news %}
							<div class="grid-item article-item col-md-6 col-sm-6 col-xs-12">
								<a href="{% url 'news_detail' new.categoria.slug new.slug %}">
									<img src="/media/{{ new.imagen_thumbnail }}" class="img-responsive" alt="{{ new.titulo|safe }}">
									<div class="article-description">
										<h2 class="text-center news-title">{{ new.titulo|safe }}</h2>
										<p>{{ new.texto1|striptags|safe|truncatewords:20 }}</p>
										<p class="text-center"><a class="leermas" href="{% url 'news_detail' new.categoria.slug new.slug %}">LEER MÁS</a></p>
									</div>
								</a>
							</div>
								{% if forloop.counter|divisibleby:3 and forloop.counter < 4 %}
								<div class="grid-item article-item text-center col-md-6 col-sm-6 col-xs-12 imgthird">
											<img src="/media/{{ section_fetiche.0.image }}" class="img-cat" alt="{{ section_fetiche.0.titulo }}" title="{{ section_fetiche.0.titulo }}" style="margin:0 auto;">
										</div>
								{% endif %}
								{% if forloop.counter|divisibleby:6 and forloop.counter < 7 %}
								<div class="grid-item article-item text-center col-md-6 col-sm-6 col-xs-12">
											<img src="/media/{{ section_fetiche.1.image }}" class="img-cat" alt="{{ section_fetiche.1.titulo }}" title="{{ section_fetiche.1.titulo }}" style="margin:0 auto;">
										</div>
								{% endif %}
								{% if forloop.counter|divisibleby:9 and forloop.counter < 10 %}
								<div class="grid-item article-item text-center col-md-6 col-sm-6 col-xs-12">
											<img src="/media/{{ section_fetiche.2.image }}" class="img-cat" alt="{{ section_fetiche.2.titulo }}" title="{{ section_fetiche.2.titulo }}" style="margin:0 auto;">
										</div>
								{% endif %}	
							{% endfor %}
							<!--div class="grid-item">
								<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/orange-tree.jpg" />
							</div-->
						</div>
					</div>
				</div>

				{% if is_paginated %}
				<div class="row text-center">
				  <ul class="pagination">
				    {% if page_obj.has_previous %}
				      <li><a href="?page={{ page_obj.previous_page_number }}"><i class="icon-triangle-left"></i></a></li>
				    {% else %}
				      <li class="disabled"><a href="#"><i class="icon-triangle-left"></i></a></li>
				    {% endif %}

				    {% for num in page_obj.paginator.page_range %}
				      {% ifequal num page_obj.number %}
				        <li class="active"><a href="#">{{ num }}<span class="sr-only">(current)</span></a></li>
				      {% else %}
				        <li><a href="?page={{ num }}">{{ num }}</a></li>
				      {% endifequal %}
				    {% endfor %}

				    {% if page_obj.has_next %}
				      <li><a href="?page={{ page_obj.next_page_number }}"><i class="icon-triangle-right"></i></a></li>
				    {% else %}
				      <li class="disabled"><a href="#"><i class="icon-triangle-right"></i></a></li>
				    {% endif %}
				  <ul>
				</div>
				{% endif %}

			</div>
			<div class="col-md-3 col-sm-3 col-xs-12">
				{% include "rightbar.html" %}  
			</div>
		</div>
	</section>	
{% endblock %}
{% block js %}
<script type="text/javascript">
	$('.carousel .carousel-inner .item:eq(0)').addClass('active');
	for (var i=1; i<=$("#fullpageservices").children().length;i++)
    {
        var parimpar ="par";
        if(i%2){
            parimpar = "impar";
        }
        $('#fullpageservices .fp-tableCell .items:eq('+(i-1)+')').addClass('row-'+parimpar);
    }
	//alert('{{section.section_slide.sectionslideitem_set.all.count}}');
	var slide_length = '{{section.section_slide.sectionslideitem_set.all.count}}';
	for ( var i = 0; i < slide_length; i++ ){
		$('.carousel-indicators').append('<li data-target="#bs-carousel" data-slide-to="'+i+'" class=""></li>');
	}
	$('ol.carousel-indicators li:eq(0)').addClass('active');

	$('ul.main-menu li a').removeClass('active');
	$('.menu-home').addClass('active');
	
</script>
{% endblock %}